// Single entry point for shared types in the renderer: every renderer module
// imports types from here (`./types`), never from `@shared/types` directly, so
// the dependency on the shared layer stays in one place. Add renderer-only types
// below the re-export if any are ever needed.
// Runtime value (worktree error codes) — re-exported so renderer modules keep
// importing from './types' rather than reaching into the shared layer.
export { WORKTREE_ERROR } from '@shared/types'
export { parseBacklogTaskId } from '@shared/backlogTaskId'

export type {
  AgentDataEvent,
  AgentExitEvent,
  AgentLaunchTarget,
  AgentSession,
  AgentStatus,
  AgentTask,
  AgentTaskStatus,
  AgentUsage,
  AccountUsage,
  UsageProfile,
  UsageWindow,
  UiState,
  AppSettings,
  BranchInfo,
  BranchSwitchResult,
  CliToolFixResult,
  CliToolId,
  CliToolStatus,
  CloneArgs,
  CloneResult,
  Integration,
  IntegrationDraft,
  IntegrationProvider,
  IntegrationsState,
  IntegrationTestResult,
  RemoteRepo,
  RepoListResult,
  CustomMemoryMutationResult,
  CustomMemoryPreset,
  CustomMemoryProvider,
  FileLinkTarget,
  FileContentMatch,
  FileContentPreviewLine,
  FileContentSearchResult,
  FileOpener,
  OpenFileTargetResult,
  FileReadOptions,
  FileReadResult,
  Folder,
  FolderUpdate,
  ProfileUpdate,
  FsEntry,
  FsListResult,
  GitActionResult,
  GitDiff,
  GitDiffFile,
  GitDiffHunk,
  GitDiffLine,
  GitFileStatus,
  GitLogEntry,
  GlobalHotkeyResult,
  GitStatus,
  Language,
  LayoutPreset,
  LayoutPresetsState,
  PresetIconType,
  PresetsState,
  Profile,
  Prompt,
  PromptsState,
  RemoteFolderAddArgs,
  RemoteFolderTestResult,
  RemoteWorkspaceTarget,
  ShortcutAction,
  ShellCommandInstallResult,
  ShellCommandStatus,
  ShortcutMap,
  StartAgentArgs,
  StartAgentResult,
  TasksState,
  TerminalPreset,
  ThemeMode,
  UpdateInfo,
  UpdateProgress,
  UsagePrimary,
  Workspace,
  WorkspaceState,
  WorkspaceTab,
  WorkspaceTabs,
  WorktreeAddArgs,
  WorktreeAddResult,
  WorktreeErrorCode
} from '@shared/types'

export type { BrowserState, BrowserSelection, BrowserRequest, BrowserDesignRequest } from '@shared/browser'
